class LinksController < ApplicationController
  before_action :set_link, only: [:destroy]

  # Sets up a new link object (without saving to database) and makes it available to the view
  def new
    @link = Link.new
  end

  # Sends the url from the params hash to HashGenerator which returns a new url_short
  # Sets both attributes in the link object and proceeds to save to db.
  # Calls ensure_unique to verify uniqueness of url_short.
  # Redirects to home#index if object is saved successfuly. Renders new if not.
  def create
    link_attributes = {
      url: link_params[:url],
      url_short: HashGenerator.create_hash(link_params[:url])
    }
    @link = Link.new(link_attributes)
    @link = UniqueShortValidator.ensure_unique(@link)

    if  @link.save
      redirect_to root_path, notice: 'Link was successfully created.'
    else
      render :new
    end
  end

  # Uses destroy method in model to remove the databaseentry related to the link object
  # Redirects to home#index
  def destroy
    @link.destroy
    redirect_to root_path, notice: 'Link was successfully destroyed.'
  end

  # uses contents of params hash to find matching link entry in db
  # redirects user original url
  def short_redirect
    @link = Link.find_by(url_short: params[:url_short])

    if @link.nil?
      redirect_to root_path
    else
      redirect_to @link.url
    end
  end

  private
    # Autogenerated code from creating scafold, sets up @link object from params hash via callback before destroy action
    def set_link
      @link = Link.find(params[:id])
    end

    # Autogenerated code from creating scafold, protects you from forged params hash
    # Removed url_short since its generated internaly
    def link_params
      params.require(:link).permit(:url)
    end
end
